const nationalities = [
  { value: '', label: 'All' },
  { value: 'CAN', label: 'Canada' },
  { value: 'USA', label: 'United States' },
  { value: 'RUS', label: 'Russia' },
  { value: 'SWE', label: 'Sweden' },
  { value: 'FIN', label: 'Finland' },
  { value: 'CZE', label: 'Czech Republic' },
  { value: 'CHE', label: 'Switzerland' },
  { value: 'SVK', label: 'Slovakia' },
  { value: 'DEU', label: 'Germany' },
  { value: 'AUT', label: 'Austria' },
  { value: 'DNK', label: 'Denmark' },
  { value: 'FRA', label: 'France' },
  { value: 'LVA', label: 'Latvia' },
  { value: 'NOR', label: 'Norway' },
  { value: 'SVN', label: 'Slovenia' },
  { value: 'NLD', label: 'Netherlands' },
  { value: 'AUS', label: 'Australia' },
  { value: 'BLR', label: 'Belarus' },
  { value: 'UKR', label: 'Ukraine' },
  { value: 'KAZ', label: 'Kazakhstan' },
];

export default nationalities;
