module.exports = [
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '610:23',
          assists: 7,
          goals: 1,
          pim: 8,
          shots: 38,
          games: 29,
          hits: 30,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '02:48',
          evenTimeOnIce: '498:55',
          penaltyMinutes: '8',
          faceOffPct: 0,
          shotPct: 2.6,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 1,
          shortHandedTimeOnIce: '108:40',
          blocked: 79,
          plusMinus: -2,
          points: 8,
          shifts: 754,
          timeOnIcePerGame: '21:02',
          evenTimeOnIcePerGame: '17:12',
          shortHandedTimeOnIcePerGame: '03:44',
          powerPlayTimeOnIcePerGame: '00:05',
        },
      },
    ],
    id: 8472382,
    person: {
      id: 8472382,
      fullName: 'Andy Greene',
      link: '/api/v1/people/8472382',
    },
    jerseyNumber: '6',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '438:30',
          assists: 3,
          goals: 0,
          pim: 16,
          shots: 34,
          games: 26,
          hits: 31,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '00:37',
          evenTimeOnIce: '347:26',
          penaltyMinutes: '16',
          faceOffPct: 0,
          shotPct: 0,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '90:27',
          blocked: 33,
          plusMinus: 3,
          points: 3,
          shifts: 577,
          timeOnIcePerGame: '16:51',
          evenTimeOnIcePerGame: '13:21',
          shortHandedTimeOnIcePerGame: '03:28',
          powerPlayTimeOnIcePerGame: '00:01',
        },
      },
    ],
    id: 8473933,
    person: {
      id: 8473933,
      fullName: 'Ben Lovejoy',
      link: '/api/v1/people/8473933',
    },
    jerseyNumber: '12',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '448:16',
          assists: 7,
          goals: 9,
          pim: 14,
          shots: 83,
          games: 29,
          hits: 76,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '01:58',
          evenTimeOnIce: '362:43',
          penaltyMinutes: '14',
          faceOffPct: 47.72,
          shotPct: 10.8,
          gameWinningGoals: 1,
          overTimeGoals: 0,
          shortHandedGoals: 2,
          shortHandedPoints: 3,
          shortHandedTimeOnIce: '83:35',
          blocked: 11,
          plusMinus: 4,
          points: 16,
          shifts: 608,
          timeOnIcePerGame: '15:27',
          evenTimeOnIcePerGame: '12:30',
          shortHandedTimeOnIcePerGame: '02:52',
          powerPlayTimeOnIcePerGame: '00:04',
        },
      },
    ],
    id: 8476399,
    person: {
      id: 8476399,
      fullName: 'Blake Coleman',
      link: '/api/v1/people/8476399',
    },
    jerseyNumber: '20',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '205:08',
          assists: 3,
          goals: 2,
          pim: 4,
          shots: 19,
          games: 19,
          hits: 15,
          powerPlayGoals: 0,
          powerPlayPoints: 1,
          powerPlayTimeOnIce: '02:18',
          evenTimeOnIce: '202:08',
          penaltyMinutes: '4',
          faceOffPct: 40.12,
          shotPct: 10.5,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:42',
          blocked: 7,
          plusMinus: -8,
          points: 5,
          shifts: 278,
          timeOnIcePerGame: '10:47',
          evenTimeOnIcePerGame: '10:38',
          shortHandedTimeOnIcePerGame: '00:02',
          powerPlayTimeOnIcePerGame: '00:07',
        },
      },
    ],
    id: 8478881,
    person: {
      id: 8478881,
      fullName: 'Brett Seney',
      link: '/api/v1/people/8478881',
    },
    jerseyNumber: '43',
    position: {
      code: 'L',
      name: 'Left Wing',
      type: 'Forward',
      abbreviation: 'LW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '313:50',
          assists: 2,
          goals: 8,
          pim: 14,
          shots: 43,
          games: 24,
          hits: 52,
          powerPlayGoals: 5,
          powerPlayPoints: 5,
          powerPlayTimeOnIce: '58:39',
          evenTimeOnIce: '210:07',
          penaltyMinutes: '14',
          faceOffPct: 48.11,
          shotPct: 18.6,
          gameWinningGoals: 1,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '45:04',
          blocked: 14,
          plusMinus: -8,
          points: 10,
          shifts: 408,
          timeOnIcePerGame: '13:04',
          evenTimeOnIcePerGame: '08:45',
          shortHandedTimeOnIcePerGame: '01:52',
          powerPlayTimeOnIcePerGame: '02:26',
        },
      },
    ],
    id: 8470619,
    person: {
      id: 8470619,
      fullName: 'Brian Boyle',
      link: '/api/v1/people/8470619',
    },
    jerseyNumber: '11',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '363:43',
          ot: 1,
          shutouts: 0,
          ties: 0,
          wins: 0,
          losses: 5,
          saves: 163,
          powerPlaySaves: 11,
          shortHandedSaves: 3,
          evenSaves: 149,
          shortHandedShots: 4,
          evenShots: 170,
          powerPlayShots: 15,
          savePercentage: 0.862,
          goalAgainstAverage: 4.29,
          games: 8,
          gamesStarted: 6,
          shotsAgainst: 189,
          goalsAgainst: 26,
          timeOnIcePerGame: '45:27',
          powerPlaySavePercentage: 73.33333333333333,
          shortHandedSavePercentage: 75,
          evenStrengthSavePercentage: 87.6470588235294,
        },
      },
    ],
    id: 8471239,
    person: {
      id: 8471239,
      fullName: 'Cory Schneider',
      link: '/api/v1/people/8471239',
    },
    jerseyNumber: '35',
    position: {
      code: 'G',
      name: 'Goalie',
      type: 'Goalie',
      abbreviation: 'G',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '606:06',
          assists: 14,
          goals: 4,
          pim: 24,
          shots: 53,
          games: 29,
          hits: 43,
          powerPlayGoals: 2,
          powerPlayPoints: 4,
          powerPlayTimeOnIce: '50:38',
          evenTimeOnIce: '541:41',
          penaltyMinutes: '24',
          faceOffPct: 0,
          shotPct: 7.5,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 1,
          shortHandedTimeOnIce: '13:47',
          blocked: 23,
          plusMinus: -10,
          points: 18,
          shifts: 767,
          timeOnIcePerGame: '20:54',
          evenTimeOnIcePerGame: '18:40',
          shortHandedTimeOnIcePerGame: '00:28',
          powerPlayTimeOnIcePerGame: '01:44',
        },
      },
    ],
    id: 8476923,
    person: {
      id: 8476923,
      fullName: 'Damon Severson',
      link: '/api/v1/people/8476923',
    },
    jerseyNumber: '28',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '76:50',
          assists: 0,
          goals: 1,
          pim: 2,
          shots: 11,
          games: 7,
          hits: 11,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '02:09',
          evenTimeOnIce: '73:48',
          penaltyMinutes: '2',
          faceOffPct: 100,
          shotPct: 9.1,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:53',
          blocked: 4,
          plusMinus: -5,
          points: 1,
          shifts: 100,
          timeOnIcePerGame: '10:58',
          evenTimeOnIcePerGame: '10:32',
          shortHandedTimeOnIcePerGame: '00:07',
          powerPlayTimeOnIcePerGame: '00:18',
        },
      },
    ],
    id: 8471226,
    person: {
      id: 8471226,
      fullName: 'Drew Stafford',
      link: '/api/v1/people/8471226',
    },
    jerseyNumber: '18',
    position: {
      code: 'R',
      name: 'Right Wing',
      type: 'Forward',
      abbreviation: 'RW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '179:01',
          assists: 3,
          goals: 1,
          pim: 4,
          shots: 10,
          games: 11,
          hits: 3,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '00:14',
          evenTimeOnIce: '178:42',
          penaltyMinutes: '4',
          faceOffPct: 0,
          shotPct: 10,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:05',
          blocked: 7,
          plusMinus: -5,
          points: 4,
          shifts: 239,
          timeOnIcePerGame: '16:16',
          evenTimeOnIcePerGame: '16:14',
          shortHandedTimeOnIcePerGame: '00:00',
          powerPlayTimeOnIcePerGame: '00:01',
        },
      },
    ],
    id: 8480948,
    person: {
      id: 8480948,
      fullName: 'Egor Yakovlev',
      link: '/api/v1/people/8480948',
    },
    jerseyNumber: '74',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '217:19',
          assists: 9,
          goals: 2,
          pim: 6,
          shots: 29,
          games: 15,
          hits: 10,
          powerPlayGoals: 0,
          powerPlayPoints: 2,
          powerPlayTimeOnIce: '26:00',
          evenTimeOnIce: '190:59',
          penaltyMinutes: '6',
          faceOffPct: 0,
          shotPct: 6.9,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:20',
          blocked: 5,
          plusMinus: -5,
          points: 11,
          shifts: 280,
          timeOnIcePerGame: '14:29',
          evenTimeOnIcePerGame: '12:43',
          shortHandedTimeOnIcePerGame: '00:01',
          powerPlayTimeOnIcePerGame: '01:44',
        },
      },
    ],
    id: 8479407,
    person: {
      id: 8479407,
      fullName: 'Jesper Bratt',
      link: '/api/v1/people/8479407',
    },
    jerseyNumber: '63',
    position: {
      code: 'L',
      name: 'Left Wing',
      type: 'Forward',
      abbreviation: 'LW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '124:12',
          assists: 1,
          goals: 1,
          pim: 4,
          shots: 17,
          games: 11,
          hits: 16,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '00:09',
          evenTimeOnIce: '114:02',
          penaltyMinutes: '4',
          faceOffPct: 0,
          shotPct: 5.9,
          gameWinningGoals: 1,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '10:01',
          blocked: 4,
          plusMinus: -2,
          points: 2,
          shifts: 173,
          timeOnIcePerGame: '11:17',
          evenTimeOnIcePerGame: '10:22',
          shortHandedTimeOnIcePerGame: '00:54',
          powerPlayTimeOnIcePerGame: '00:00',
        },
      },
    ],
    id: 8479315,
    person: {
      id: 8479315,
      fullName: 'Joey Anderson',
      link: '/api/v1/people/8479315',
    },
    jerseyNumber: '49',
    position: {
      code: 'R',
      name: 'Right Wing',
      type: 'Forward',
      abbreviation: 'RW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '59:58',
          assists: 0,
          goals: 0,
          pim: 0,
          shots: 3,
          games: 5,
          hits: 7,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '03:28',
          evenTimeOnIce: '56:30',
          penaltyMinutes: '0',
          faceOffPct: 42.85,
          shotPct: 0,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:00',
          blocked: 3,
          plusMinus: 2,
          points: 0,
          shifts: 78,
          timeOnIcePerGame: '11:59',
          evenTimeOnIcePerGame: '11:18',
          shortHandedTimeOnIcePerGame: '00:00',
          powerPlayTimeOnIcePerGame: '00:41',
        },
      },
    ],
    id: 8477961,
    person: {
      id: 8477961,
      fullName: 'John Quenneville',
      link: '/api/v1/people/8477961',
    },
    jerseyNumber: '47',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '1384:53',
          ot: 5,
          shutouts: 3,
          ties: 0,
          wins: 10,
          losses: 8,
          saves: 653,
          powerPlaySaves: 82,
          shortHandedSaves: 21,
          evenSaves: 550,
          shortHandedShots: 22,
          evenShots: 606,
          powerPlayShots: 95,
          savePercentage: 0.903,
          goalAgainstAverage: 3.03,
          games: 24,
          gamesStarted: 23,
          shotsAgainst: 723,
          goalsAgainst: 70,
          timeOnIcePerGame: '57:42',
          powerPlaySavePercentage: 86.31578947368422,
          shortHandedSavePercentage: 95.45454545454545,
          evenStrengthSavePercentage: 90.75907590759076,
        },
      },
    ],
    id: 8476234,
    person: {
      id: 8476234,
      fullName: 'Keith Kinkaid',
      link: '/api/v1/people/8476234',
    },
    jerseyNumber: '1',
    position: {
      code: 'G',
      name: 'Goalie',
      type: 'Goalie',
      abbreviation: 'G',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '534:10',
          assists: 11,
          goals: 16,
          pim: 18,
          shots: 88,
          games: 29,
          hits: 45,
          powerPlayGoals: 6,
          powerPlayPoints: 10,
          powerPlayTimeOnIce: '96:44',
          evenTimeOnIce: '426:31',
          penaltyMinutes: '18',
          faceOffPct: 29.41,
          shotPct: 18.2,
          gameWinningGoals: 2,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '10:55',
          blocked: 18,
          plusMinus: 0,
          points: 27,
          shifts: 639,
          timeOnIcePerGame: '18:25',
          evenTimeOnIcePerGame: '14:42',
          shortHandedTimeOnIcePerGame: '00:22',
          powerPlayTimeOnIcePerGame: '03:20',
        },
      },
    ],
    id: 8475151,
    person: {
      id: 8475151,
      fullName: 'Kyle Palmieri',
      link: '/api/v1/people/8475151',
    },
    jerseyNumber: '21',
    position: {
      code: 'R',
      name: 'Right Wing',
      type: 'Forward',
      abbreviation: 'RW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '418:18',
          assists: 6,
          goals: 6,
          pim: 6,
          shots: 61,
          games: 27,
          hits: 12,
          powerPlayGoals: 1,
          powerPlayPoints: 3,
          powerPlayTimeOnIce: '61:48',
          evenTimeOnIce: '356:18',
          penaltyMinutes: '6',
          faceOffPct: 23.52,
          shotPct: 9.8,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:12',
          blocked: 9,
          plusMinus: -9,
          points: 12,
          shifts: 521,
          timeOnIcePerGame: '15:29',
          evenTimeOnIcePerGame: '13:11',
          shortHandedTimeOnIcePerGame: '00:00',
          powerPlayTimeOnIcePerGame: '02:17',
        },
      },
    ],
    id: 8475149,
    person: {
      id: 8475149,
      fullName: 'Marcus Johansson',
      link: '/api/v1/people/8475149',
    },
    jerseyNumber: '90',
    position: {
      code: 'L',
      name: 'Left Wing',
      type: 'Forward',
      abbreviation: 'LW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '380:29',
          assists: 5,
          goals: 2,
          pim: 33,
          shots: 65,
          games: 29,
          hits: 52,
          powerPlayGoals: 0,
          powerPlayPoints: 1,
          powerPlayTimeOnIce: '29:06',
          evenTimeOnIce: '351:16',
          penaltyMinutes: '33',
          faceOffPct: 0,
          shotPct: 3.1,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:07',
          blocked: 13,
          plusMinus: -7,
          points: 7,
          shifts: 501,
          timeOnIcePerGame: '13:07',
          evenTimeOnIcePerGame: '12:06',
          shortHandedTimeOnIcePerGame: '00:00',
          powerPlayTimeOnIcePerGame: '01:00',
        },
      },
    ],
    id: 8477425,
    person: {
      id: 8477425,
      fullName: 'Miles Wood',
      link: '/api/v1/people/8477425',
    },
    jerseyNumber: '44',
    position: {
      code: 'L',
      name: 'Left Wing',
      type: 'Forward',
      abbreviation: 'LW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '436:40',
          assists: 5,
          goals: 0,
          pim: 9,
          shots: 19,
          games: 23,
          hits: 31,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '03:11',
          evenTimeOnIce: '391:35',
          penaltyMinutes: '9',
          faceOffPct: 0,
          shotPct: 0,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '41:54',
          blocked: 24,
          plusMinus: -5,
          points: 5,
          shifts: 583,
          timeOnIcePerGame: '18:59',
          evenTimeOnIcePerGame: '17:01',
          shortHandedTimeOnIcePerGame: '01:49',
          powerPlayTimeOnIcePerGame: '00:08',
        },
      },
    ],
    id: 8477509,
    person: {
      id: 8477509,
      fullName: 'Mirco Mueller',
      link: '/api/v1/people/8477509',
    },
    jerseyNumber: '25',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '450:17',
          assists: 13,
          goals: 6,
          pim: 2,
          shots: 56,
          games: 25,
          hits: 12,
          powerPlayGoals: 2,
          powerPlayPoints: 5,
          powerPlayTimeOnIce: '89:59',
          evenTimeOnIce: '349:26',
          penaltyMinutes: '2',
          faceOffPct: 41.64,
          shotPct: 10.7,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '10:52',
          blocked: 12,
          plusMinus: -1,
          points: 19,
          shifts: 528,
          timeOnIcePerGame: '18:00',
          evenTimeOnIcePerGame: '13:58',
          shortHandedTimeOnIcePerGame: '00:26',
          powerPlayTimeOnIcePerGame: '03:35',
        },
      },
    ],
    id: 8480002,
    person: {
      id: 8480002,
      fullName: 'Nico Hischier',
      link: '/api/v1/people/8480002',
    },
    jerseyNumber: '13',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '372:30',
          assists: 0,
          goals: 4,
          pim: 9,
          shots: 31,
          games: 24,
          hits: 27,
          powerPlayGoals: 1,
          powerPlayPoints: 1,
          powerPlayTimeOnIce: '21:49',
          evenTimeOnIce: '297:13',
          penaltyMinutes: '9',
          faceOffPct: 48.23,
          shotPct: 12.9,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '53:28',
          blocked: 13,
          plusMinus: -2,
          points: 4,
          shifts: 486,
          timeOnIcePerGame: '15:31',
          evenTimeOnIcePerGame: '12:23',
          shortHandedTimeOnIcePerGame: '02:13',
          powerPlayTimeOnIcePerGame: '00:54',
        },
      },
    ],
    id: 8478401,
    person: {
      id: 8478401,
      fullName: 'Pavel Zacha',
      link: '/api/v1/people/8478401',
    },
    jerseyNumber: '37',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '579:04',
          assists: 11,
          goals: 1,
          pim: 14,
          shots: 63,
          games: 26,
          hits: 43,
          powerPlayGoals: 1,
          powerPlayPoints: 2,
          powerPlayTimeOnIce: '61:30',
          evenTimeOnIce: '467:45',
          penaltyMinutes: '14',
          faceOffPct: 0,
          shotPct: 1.6,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '49:49',
          blocked: 40,
          plusMinus: -7,
          points: 12,
          shifts: 687,
          timeOnIcePerGame: '22:16',
          evenTimeOnIcePerGame: '17:59',
          shortHandedTimeOnIcePerGame: '01:54',
          powerPlayTimeOnIcePerGame: '02:21',
        },
      },
    ],
    id: 8475222,
    person: {
      id: 8475222,
      fullName: 'Sami Vatanen',
      link: '/api/v1/people/8475222',
    },
    jerseyNumber: '45',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '247:46',
          assists: 3,
          goals: 2,
          pim: 16,
          shots: 28,
          games: 20,
          hits: 43,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '24:27',
          evenTimeOnIce: '222:38',
          penaltyMinutes: '16',
          faceOffPct: 41.46,
          shotPct: 7.1,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:41',
          blocked: 12,
          plusMinus: -4,
          points: 5,
          shifts: 329,
          timeOnIcePerGame: '12:23',
          evenTimeOnIcePerGame: '11:07',
          shortHandedTimeOnIcePerGame: '00:02',
          powerPlayTimeOnIcePerGame: '01:13',
        },
      },
    ],
    id: 8476474,
    person: {
      id: 8476474,
      fullName: 'Stefan Noesen',
      link: '/api/v1/people/8476474',
    },
    jerseyNumber: '23',
    position: {
      code: 'R',
      name: 'Right Wing',
      type: 'Forward',
      abbreviation: 'RW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '02:33',
          assists: 0,
          goals: 0,
          pim: 0,
          shots: 0,
          games: 1,
          hits: 1,
          powerPlayGoals: 0,
          powerPlayPoints: 0,
          powerPlayTimeOnIce: '00:00',
          evenTimeOnIce: '02:33',
          penaltyMinutes: '0',
          faceOffPct: 0,
          shotPct: 0,
          gameWinningGoals: 0,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '00:00',
          blocked: 0,
          plusMinus: 0,
          points: 0,
          shifts: 2,
          timeOnIcePerGame: '02:33',
          evenTimeOnIcePerGame: '02:33',
          shortHandedTimeOnIcePerGame: '00:00',
          powerPlayTimeOnIcePerGame: '00:00',
        },
      },
    ],
    id: 8477463,
    person: {
      id: 8477463,
      fullName: 'Steven Santini',
      link: '/api/v1/people/8477463',
    },
    jerseyNumber: '16',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '573:01',
          assists: 23,
          goals: 8,
          pim: 16,
          shots: 97,
          games: 29,
          hits: 20,
          powerPlayGoals: 0,
          powerPlayPoints: 11,
          powerPlayTimeOnIce: '100:41',
          evenTimeOnIce: '470:58',
          penaltyMinutes: '16',
          faceOffPct: 45.45,
          shotPct: 8.2,
          gameWinningGoals: 2,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '01:22',
          blocked: 27,
          plusMinus: -7,
          points: 31,
          shifts: 645,
          timeOnIcePerGame: '19:45',
          evenTimeOnIcePerGame: '16:14',
          shortHandedTimeOnIcePerGame: '00:02',
          powerPlayTimeOnIcePerGame: '03:28',
        },
      },
    ],
    id: 8475791,
    person: {
      id: 8475791,
      fullName: 'Taylor Hall',
      link: '/api/v1/people/8475791',
    },
    jerseyNumber: '9',
    position: {
      code: 'L',
      name: 'Left Wing',
      type: 'Forward',
      abbreviation: 'LW',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '515:22',
          assists: 8,
          goals: 9,
          pim: 6,
          shots: 39,
          games: 28,
          hits: 26,
          powerPlayGoals: 0,
          powerPlayPoints: 2,
          powerPlayTimeOnIce: '51:02',
          evenTimeOnIce: '390:54',
          penaltyMinutes: '6',
          faceOffPct: 54.2,
          shotPct: 23.1,
          gameWinningGoals: 1,
          overTimeGoals: 0,
          shortHandedGoals: 1,
          shortHandedPoints: 1,
          shortHandedTimeOnIce: '73:26',
          blocked: 12,
          plusMinus: -1,
          points: 17,
          shifts: 649,
          timeOnIcePerGame: '18:24',
          evenTimeOnIcePerGame: '13:57',
          shortHandedTimeOnIcePerGame: '02:37',
          powerPlayTimeOnIcePerGame: '01:49',
        },
      },
    ],
    id: 8471233,
    person: {
      id: 8471233,
      fullName: 'Travis Zajac',
      link: '/api/v1/people/8471233',
    },
    jerseyNumber: '19',
    position: {
      code: 'C',
      name: 'Center',
      type: 'Forward',
      abbreviation: 'C',
    },
  },
  {
    teamId: 1,
    stats: [
      {
        season: '20182019',
        stat: {
          timeOnIce: '518:29',
          assists: 8,
          goals: 2,
          pim: 0,
          shots: 46,
          games: 28,
          hits: 12,
          powerPlayGoals: 0,
          powerPlayPoints: 7,
          powerPlayTimeOnIce: '93:33',
          evenTimeOnIce: '420:26',
          penaltyMinutes: '0',
          faceOffPct: 0,
          shotPct: 4.3,
          gameWinningGoals: 1,
          overTimeGoals: 0,
          shortHandedGoals: 0,
          shortHandedPoints: 0,
          shortHandedTimeOnIce: '04:30',
          blocked: 22,
          plusMinus: 1,
          points: 10,
          shifts: 624,
          timeOnIcePerGame: '18:31',
          evenTimeOnIcePerGame: '15:00',
          shortHandedTimeOnIcePerGame: '00:09',
          powerPlayTimeOnIcePerGame: '03:20',
        },
      },
    ],
    id: 8477355,
    person: {
      id: 8477355,
      fullName: 'Will Butcher',
      link: '/api/v1/people/8477355',
    },
    jerseyNumber: '8',
    position: {
      code: 'D',
      name: 'Defenseman',
      type: 'Defenseman',
      abbreviation: 'D',
    },
  },
];
